my:
  name: huanhuan
  age: 22
  number: ${random.int}
  uuid: ${random.uuid}
  max: ${random.int(10)}
  value: ${random.value}
  greeting: hi,i'm ${my.name}
  aFree: hahaha
#选择环境
spring:
  profiles:
    active: test

#配置Actuator 运行状态监控
management:
  server:
    port: 9001
    servlet:
      enable: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always